name:                conway
version:             0.1.0.0
github:              "ssangervasi/conway"
license:             MIT
author:              "Sebastian Sangervasi"
maintainer:          "sorrymyemailaddressisverylong@gmail.com"
copyright:           "2018 Sebastian Sangervasi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ssangervasi/conway#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.14 && < 1

library:
  source-dirs: src

executables:
  conway-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - conway

tests:
  conway-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conway
